import type { Metadata } from "next";
import Link from "next/link";
import Reveal from "../components/Reveal";
import ModelLabGlobe from "../components/ModelLabGlobe";

export const metadata: Metadata = {
  title: "Updates",
  description:
    "What changed in the CRI Engine, as it ships. October 2026: the resident agent runs with no API key and an optional fully-local model, and a new Model Lab builds physics-based hazard models from scratch — validated across 37 cities worldwide.",
};

// Validated = report.md's "validated" + "validated after diagnosis"; No model = "no model" + "other (too few events to hindcast)".
const SWEEP_TABLE = [
  { hazard: "Extreme heat", n: 37, validated: 15, drift: 22, failed: 0, noModel: 0 },
  { hazard: "Extreme wind", n: 37, validated: 27, drift: 8, failed: 2, noModel: 0 },
  { hazard: "Fire weather", n: 37, validated: 22, drift: 10, failed: 4, noModel: 1 },
  { hazard: "Extreme rainfall", n: 37, validated: 24, drift: 3, failed: 10, noModel: 0 },
  { hazard: "Earthquake", n: 37, validated: 16, drift: 0, failed: 1, noModel: 20 },
  { hazard: "Tropical cyclone", n: 37, validated: 6, drift: 0, failed: 2, noModel: 29 },
];

export default function UpdatesPage() {
  return (
    <div className="pt-40 pb-32 px-6">
      <div className="max-w-4xl mx-auto mb-20">
        <Reveal>
          <p className="text-xs uppercase tracking-widest text-gold-200 font-mono mb-3">Updates</p>
          <h1 className="heading-xl grad-text mb-6 text-balance">
            What shipped, <span className="grad-gold">as it ships.</span>
          </h1>
          <p className="text-lg text-zinc-400 leading-relaxed max-w-2xl">
            Not a marketing changelog — the same engineering log the team uses internally, in plain
            language. First entry: the agent stopped needing anyone else's AI, and the engine learned
            to build and verify its own hazard models from scratch.
          </p>
        </Reveal>
      </div>

      {/* Timeline rail */}
      <div className="max-w-4xl mx-auto relative">
        <div
          className="absolute top-2 bottom-0 w-px bg-gradient-to-b from-gold-200/50 via-white/10 to-transparent"
          style={{ left: "5px" }}
          aria-hidden
        />

        {/* ── Entry: 8 October 2026 ───────────────────────────────────── */}
        <div className="relative pl-10 pb-24">
          <span className="absolute left-0 top-1.5 w-[11px] h-[11px] rounded-full bg-gold-200 shadow-[0_0_12px_rgba(212,175,55,0.7)]" />
          <Reveal>
            <p className="text-xs font-mono text-zinc-600 mb-2">8 October 2026 · App 1.1</p>
            <h2 className="heading-lg grad-text mb-5">An engine that tests itself.</h2>
            <p className="text-zinc-400 leading-relaxed max-w-2xl mb-14">
              Two changes, shipped together. The resident agent no longer depends on anyone else's AI
              vendor — not even an API key. And a new Model Lab inside the engine can build a
              physics-based hazard model from scratch at any coordinate on request, verify it against
              five to seven internal consistency tests, and say plainly whether it holds up against the
              historical record. We ran it at 37 cities across every inhabited climate zone and
              published the result below, failures included.
            </p>
          </Reveal>

          {/* Independent AI */}
          <Reveal delayMs={60}>
            <div id="independent-ai" className="scroll-mt-28 mb-16">
              <h3 className="text-sm font-mono text-gold-200 uppercase tracking-widest mb-4">Independent, by default</h3>
              <div className="grid sm:grid-cols-3 gap-5">
                <div className="panel p-6 h-full">
                  <h4 className="text-sm font-semibold text-white mb-2">No API Key, No Vendor</h4>
                  <p className="text-xs text-zinc-500 leading-relaxed">
                    The chat panel used to run on a third-party model (Groq · llama-3.3-70b). It now
                    answers by default from the sources the engine has itself learned — assembled, not
                    generated by an outside API — so nothing about a client's assessment ever leaves
                    their machine to reach a language-model vendor.
                  </p>
                </div>
                <div className="panel p-6 h-full">
                  <h4 className="text-sm font-semibold text-white mb-2">Optional, Fully Local Model</h4>
                  <p className="text-xs text-zinc-500 leading-relaxed">
                    For more fluent written answers, the installer offers a free language model that
                    runs on the user's own Mac via Ollama — about a 2 GB download, no account, no key,
                    no cloud call ever made. The engine detects it automatically; without it, the agent
                    still answers, just by assembling the most relevant sentences from its sources.
                  </p>
                </div>
                <div className="panel p-6 h-full">
                  <h4 className="text-sm font-semibold text-white mb-2">An Autopilot Inbox</h4>
                  <p className="text-xs text-zinc-500 leading-relaxed">
                    The resident agent now works in the background while the app is simply open —
                    scanning live hazards, re-running watched sites against the 3D twin, drafting posts —
                    and reports back when asked: <span className="text-zinc-400">"What did you find while I was away?"</span>
                  </p>
                </div>
              </div>
            </div>
          </Reveal>

          {/* Model Lab */}
          <Reveal delayMs={100}>
            <div id="model-lab" className="scroll-mt-28 mb-16">
              <h3 className="text-sm font-mono text-gold-200 uppercase tracking-widest mb-4">Model Lab</h3>
              <p className="text-zinc-400 leading-relaxed max-w-2xl mb-6">
                Ask the agent to build a model and it does the work a hazard modeller would: picks the
                physics, pulls terrain and reanalysis data, runs the model, puts it through verification
                tests, checks it against the historical record, and writes up the method and the result
                in plain language — across twelve hazard types, from flood inundation and fire weather
                to earthquake recurrence and storm surge.
              </p>
              <div className="rounded-xl overflow-hidden border border-white/8">
                <div className="flex items-center gap-2 px-4 py-3 bg-black/30 border-b border-white/6">
                  <span className="w-2.5 h-2.5 rounded-full bg-red-500/60" />
                  <span className="w-2.5 h-2.5 rounded-full bg-yellow-500/60" />
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/60" />
                  <span className="ml-3 text-xs text-zinc-600 font-mono">model-lab · flood · 22.2645, 91.805</span>
                </div>
                <div className="bg-[#030912] p-5 font-mono text-xs text-zinc-400 leading-relaxed space-y-1">
                  <div className="text-zinc-300">&gt; build a flood model for 22.2645, 91.805</div>
                  <div className="h-2" />
                  <div>Starting a flood inundation study for 22.2645, 91.8050. I will work through: physics</div>
                  <div>choice, terrain and rainfall data, model run, five verification tests, sensitivity,</div>
                  <div>then write the methods and results.</div>
                  <div className="h-2" />
                  <div>Status              verified only</div>
                  <div>Verification        7 of 7 tests passed</div>
                  <div>Peak depth at site   0.01 m</div>
                  <div>Time under water     0.0 h</div>
                  <div>Area &gt; 30 cm deep    0.83 km² (of 10.1 km²)</div>
                  <div>Design storm         100-year, 172 mm in 6 h</div>
                  <div>Biggest uncertainty  Surface roughness (Manning n)</div>
                  <div>Calibrated/validated no: no observations supplied</div>
                </div>
              </div>
              <p className="text-xs text-zinc-600 mt-3">
                33 seconds, start to finished write-up. "Verified only" is the model's own honest ceiling
                here — there were no gauge observations at this site to calibrate or validate against,
                and it says so rather than implying more confidence than the data supports.
              </p>
            </div>
          </Reveal>

          {/* Global sweep */}
          <Reveal delayMs={140}>
            <div id="global-sweep" className="scroll-mt-28">
              <h3 className="text-sm font-mono text-gold-200 uppercase tracking-widest mb-4">The Global Sweep</h3>
              <p className="text-zinc-400 leading-relaxed max-w-2xl mb-10">
                We pointed Model Lab at 37 cities spanning every inhabited climate zone — tropical
                rainforest to subarctic, small island to high-altitude desert — and ran all six
                extreme-value hazards at every site it could reach: 222 studies in total. The map plots
                every one of them; hover a point for its hazard-by-hazard result.
              </p>
            </div>
          </Reveal>

          <Reveal delayMs={160}>
            <div className="panel p-6 sm:p-8 mb-10">
              <ModelLabGlobe />
            </div>
          </Reveal>

          <Reveal delayMs={180}>
            <div className="overflow-x-auto mb-8">
              <table className="w-full text-sm border-collapse">
                <thead>
                  <tr className="border-b border-white/10 text-left text-xs text-zinc-500 uppercase tracking-wide">
                    <th className="py-2 pr-4 font-medium">Hazard</th>
                    <th className="py-2 px-3 font-medium text-right">Sites</th>
                    <th className="py-2 px-3 font-medium text-right">Validated</th>
                    <th className="py-2 px-3 font-medium text-right">Small drift</th>
                    <th className="py-2 px-3 font-medium text-right">Hindcast failed</th>
                    <th className="py-2 pl-3 font-medium text-right">No model (no exposure/data)</th>
                  </tr>
                </thead>
                <tbody className="font-mono text-xs">
                  {SWEEP_TABLE.map((r) => (
                    <tr key={r.hazard} className="border-b border-white/5">
                      <td className="py-2.5 pr-4 text-white font-sans">{r.hazard}</td>
                      <td className="py-2.5 px-3 text-right text-zinc-400">{r.n}</td>
                      <td className="py-2.5 px-3 text-right text-gold-200">{r.validated}</td>
                      <td className="py-2.5 px-3 text-right text-zinc-400">{r.drift}</td>
                      <td className="py-2.5 px-3 text-right text-red-400">{r.failed}</td>
                      <td className="py-2.5 pl-3 text-right text-zinc-600">{r.noModel}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Reveal>

          <Reveal delayMs={200}>
            <div className="grid sm:grid-cols-3 gap-5 mb-10">
              <div className="panel p-5">
                <h4 className="text-sm font-semibold text-white mb-2">153 of 222 Clean, Failures Disclosed</h4>
                <p className="text-xs text-zinc-500 leading-relaxed">
                  69% validated outright or with a small, statistically real drift. Narrowed to just the
                  four extreme-value hazards — rain, wind, fire, heat, the ones run against a historical
                  hindcast — 88 of 147 passed outright (nominal false-fail rate ≈10%). One real bug
                  surfaced mid-sweep and is listed, not hidden: a fire-weather run at Riyadh hit a type
                  error on a hyper-arid site (about 46 mm of rain a year) where no fire-weather model
                  should apply; fixed, it now correctly returns "no model" instead of crashing. "No
                  model" otherwise means exactly what it says — a cyclone or earthquake run at a site
                  with no meaningful exposure to that hazard.
                </p>
              </div>
              <div className="panel p-5">
                <h4 className="text-sm font-semibold text-white mb-2">Some "Failures" Are the Finding</h4>
                <p className="text-xs text-zinc-500 leading-relaxed">
                  At Dhaka, Shanghai, Cape Town, London, New York, Manila and others, the rainfall or
                  fire hindcast "failed" because the recent record is systematically higher than the
                  early record predicted — the hazard itself is intensifying. The engine reports that as
                  a finding, not a modelling error, and names which direction it moved.
                </p>
              </div>
              <div className="panel p-5">
                <h4 className="text-sm font-semibold text-white mb-2">A Physical Sanity Check, Too</h4>
                <p className="text-xs text-zinc-500 leading-relaxed">
                  The earthquake model's own Gutenberg–Richter b-value came back with a median of 1.06
                  across 17 sites (range 0.80–1.50) — close to the 1.0 seismologists expect from a
                  well-behaved catalogue, a physical consistency check independent of the hindcast.
                </p>
              </div>
            </div>
          </Reveal>

          <Reveal delayMs={220}>
            <div className="flex flex-wrap gap-4">
              <Link href="/platform#model-lab" className="btn-primary">See Model Lab on the Platform page</Link>
              <Link href="/validation" className="btn-ghost">Read the full validation record</Link>
            </div>
          </Reveal>
        </div>
      </div>
    </div>
  );
}
